pool:
  name: kfmrgnmn
  demands: maven


steps:
- task: Maven@3
  displayName: 'Maven complete/pom.xml'
  inputs:
    mavenPomFile: complete/pom.xml
    goals: install
    publishJUnitResults: false
    javaHomeOption: '$(Parameters.javaHomeSelection)'
    jdkDirectory: '$(Parameters.jdkUserInputPath)'
    mavenVersionOption: Path
    mavenDirectory: '$(Parameters.mavenPath)'
    mavenSetM2Home: '$(Parameters.mavenSetM2Home)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
